WIP - changes for KNIDEPLOY-2111
openshift-kni/baremetal-deploy pull request #766
Opened 2021-05-24 11:36 UTC by aireilly

# Description

If the MAC address of an existing ironic node and a Bare Metal host matches, then the operator will associate the two. When the host enrollment, inspection, cleaning, or other ironic steps fail, the baremetal-operator will continuously retry. Need to let users know it will retry.

Documents #KNI-2111

## Type of change

Please select the appropriate options:

- [x] This change is a documentation update

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] If a change is adding a feature, it should require a change to the README.md and the review should catch this.
- [ ] If the change is a fix, it should have an issue. The review should make sure the comments state the issue (not just the number) and it should use the keywords that will close the issue on merge.
- [ ] A change should not be merged unless it passes CI or there is a comment/update saying what testing was passed.
- [ ] PRs should not be merged unless positively reviewed.

2021-05-24 11:51 UTC, iranzo approved these changes
/lgtm
/approve

2021-05-24 11:51 UTC, iranzo commented
/hold

2021-05-27 15:58 UTC, johnwilkins approved these changes
LGTM. However, I sort of loath using both the term "node" and the term "host" in the same sentence. I wish there were a better way of stating this. Linux expressly uses the term host and hostname for example. I prefer node to host and server, but it's a personal thing.

2021-05-27 16:02 UTC, iranzo commented
> LGTM. However, I sort of loath using both the term "node" and the term "host" in the same sentence. I wish there were a better way of stating this. Linux expressly uses the term host and hostname for example. I prefer node to host and server, but it's a personal thing.

do a /hold cancel  once it's ready for merging

2021-05-27 16:22 UTC, aireilly commented
@johnwilkins @iranzo John to your point - in this instance, and in OCP, a "bare metal node" is explicilty a host which has been provisioned as a machine in the cluster, while a "bare metal host" has not yet been provisioned as a "bare metal node" in the cluster. Correct me if I am wrong /honk

2021-06-01 08:59 UTC, aireilly commented
@johnwilkins @iranzo I've added some more detail on how to diagnose a dupe MAC address when adding a host to the cluster, it's in a new module.

2021-06-02 13:18 UTC, honza commented
/lgtm

2021-06-04 10:32 UTC, iranzo requested changes
Hi, if the PR is no longer WIP, edit the title to remove it, if not, it will not be mergeable.

Also, @johnwilkins WDT? anything else or can be merged?

Thx

2021-06-08 08:58 UTC, aireilly commented
Waiting for final review from @johnwilkins before merge.

2021-06-08 17:45 UTC, johnwilkins reviewed
Just a few comments.

2021-06-08 17:45 UTC, johnwilkins commented on documentation/ipi-install/modules/ipi-install-diagnosing-duplicate-mac-address.adoc
> +If the MAC address of an existing bare metal node in the cluster matches the MAC address of a bare metal host that you are attempting to add to the cluster, the Ironic installation operator associate
s/operator/Operator/  The Operator displays a registration error.

2021-06-08 17:45 UTC, johnwilkins commented on documentation/ipi-install/modules/ipi-install-diagnosing-duplicate-mac-address.adoc
> +. Get the pods that are running in the openshift-machine-api:
`openshift-machine-api`

2021-06-10 09:46 UTC, aireilly commented
> Hi, if the PR is no longer WIP, edit the title to remove it, if not, it will not be mergeable.
> 
> Also, @johnwilkins WDT? anything else or can be merged?
> 
> Thx

This is ready to merge now.

2021-06-11 11:43 UTC, iranzo commented
/hold cancel

2021-06-11 11:43 UTC, iranzo commented
/ok-to-test

2021-06-11 11:46 UTC, merged